- name: Upgrade pip
#   pip: name=pip3 state=latest executable=/usr/local/bin/pip3
  pip: name=pip state=latest
  ignore_errors: yes

- name: Install pip3 packages
  pip:
    name:
    - requests
    - pyyaml
    - jmespath
    # - firewalld
    # - ansible
