alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias python='python3'
alias cd2='cd ../..'
alias cd3='cd ../../..'
alias perm='stat -c "%a %n" '
alias ghi='history|grep'
alias dnfs='dnf search'
alias dnfi='sudo dnf install -y'
alias dco='docker-compose'
alias lss='ls -lhFAS'
alias dps='docker ps -a'
alias dsp='docker system prune -f --volumes'
alias dl='docker logs -f'
alias dx='docker exec -it'
alias dbt='docker build . -t'
alias di='docker images'
alias dr='docker run -it'
alias drm='docker rm'
alias drmi='docker rmi'
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
